std = "roblox"

[rules]
constant_table_comparison = "deny"
deprecated = "warn"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "warn"
high_cyclomatic_complexity = "warn"
if_same_then_else = "deny"
ifs_same_cond = "warn"
incorrect_standard_library_use = "deny"
mismatched_arg_count = "deny"
multiple_statements = "warn"
must_use = "deny"
parenthese_conditions = "warn"
shadowing = "deny"
type_check_inside_call = "warn"
unbalanced_assignments = "warn"
undefined_variable = "warn"
unscoped_variables = "warn"
unused_variable = "warn"
mixed_table = "allow"